# PlayerSpawn 配置

# 默认重生设置
default:
  # 全服务器默认重生点
  server:
    enabled: true  # 是否启用
    location:      # 位置
      world: world  # 世界名称
      x: 0         # X 坐标
      y: 64        # Y 坐标
      z: 0         # Z 坐标
      yaw: 0       # 水平旋转角度
      pitch: 0     # 垂直旋转角度
  
  # 世界特定的默认重生点
  worlds:
    world:
      enabled: false  # 是否启用
      location:       # 位置
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度
    world_nether:
      enabled: false  # 是否启用
      location:       # 位置
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度

# 新玩家重生设置
new_player:
  # 是否为新玩家使用自定义重生点
  enabled: true  # 是否启用
  # 如果未指定，则使用默认重生点
  use_default_if_not_specified: true
  location:      # 位置
    world: world  # 世界名称
    x: 0         # X 坐标
    y: 64        # Y 坐标
    z: 0         # Z 坐标
    yaw: 0       # 水平旋转角度
    pitch: 0     # 垂直旋转角度

# 重生设置
respawn:
  # 是否使用自定义重生点
  enabled: true  # 是否启用
  # 如果可用，使用玩家的重生点
  use_player_spawn: true
  # 如果未指定，则使用默认重生点
  use_default_if_not_specified: true
  # 全服务器重生点
  server:
    enabled: false  # 是否启用
    location:       # 位置
      world: world  # 世界名称
      x: 0         # X 坐标
      y: 64        # Y 坐标
      z: 0         # Z 坐标
      yaw: 0       # 水平旋转角度
      pitch: 0     # 垂直旋转角度
  # 世界特定的重生点
  worlds:
    world:
      enabled: false  # 是否启用
      location:       # 位置
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度

# 玩家加入时传送到他们的重生点
teleport_on_join: false

# 原版重生机制设置
vanilla_mechanics:
  # 是否尊重床和重生锚作为重生点 (true = 使用原版行为)
  respect_bed_and_anchor: true

# 重新加入设置
on_rejoin:
  # 当玩家重新加入服务器时的行为
  # 选项: "last_location" (传送到上次登出的位置), "spawn" (传送到重生点), "nothing" (什么都不做)
  behavior: "nothing"
  # 是否保存玩家的登出位置
  save_logout_location: true

# Floodgate (Bedrock) 玩家设置
floodgate:
  # 是否为 Floodgate 玩家启用特殊处理
  enabled: true  # 是否启用
  # 全服务器重生点 (针对 Floodgate 玩家)
  server:
    enabled: false  # 是否启用
    location:       # 位置
      world: world  # 世界名称
      x: 0         # X 坐标
      y: 64        # Y 坐标
      z: 0         # Z 坐标
      yaw: 0       # 水平旋转角度
      pitch: 0     # 垂直旋转角度
  # 世界特定的重生点 (针对 Floodgate 玩家)
  worlds:
    world:
      enabled: false  # 是否启用
      location:       # 位置
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度
  # 新玩家重生点 (针对 Floodgate 玩家)
  new_player:
    enabled: false  # 是否启用
    location:       # 位置
      world: world  # 世界名称
      x: 0         # X 坐标
      y: 64        # Y 坐标
      z: 0         # Z 坐标
      yaw: 0       # 水平旋转角度
      pitch: 0     # 垂直旋转角度
  # 重生点 (针对 Floodgate 玩家)
  respawn:
    enabled: false  # 是否启用
    # 全服务器重生点
    server:
      enabled: false  # 是否启用
      location:       # 位置
        world: world  # 世界名称
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度
    # 世界特定的重生点
    worlds:
      world:
        enabled: false  # 是否启用
        location:       # 位置
          x: 0         # X 坐标
          y: 64        # Y 坐标
          z: 0         # Z 坐标
          yaw: 0       # 水平旋转角度
          pitch: 0     # 垂直旋转角度

# 组重生设置
groups:
  default:
    server:
      enabled: false  # 是否启用
      location:       # 位置
        world: world  # 世界名称
        x: 0         # X 坐标
        y: 64        # Y 坐标
        z: 0         # Z 坐标
        yaw: 0       # 水平旋转角度
        pitch: 0     # 垂直旋转角度
    worlds:
      world:
        enabled: false  # 是否启用
        location:       # 位置
          x: 0         # X 坐标
          y: 64        # Y 坐标
          z: 0         # Z 坐标
          yaw: 0       # 水平旋转角度
          pitch: 0     # 垂直旋转角度